### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by Sandra631** [SistemasTecTlaxiaco/infografia-Sandra631-1#1]
[INFOGRAFIA_SANDRA_YOLOTZIN_REYES_GARCIA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Sandra631-1/files/8054418/INFOGRAFIA_SANDRA_YOLOTZIN_REYES_GARCIA.pdf)

**Comment by Nayee123** [comment]
Un buen trabajo 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
